package com.example.rppg.app;

import com.example.rppg.vision.RoiMode;
import com.example.signal.QualityMode;
import com.example.signal.SignalMethod;

public record Config(
        int cameraIndex,
        int targetWidth,
        int targetHeight,
        double targetFps,
        double faceSmoothingAlpha,
        double faceSmoothingMaxStep,
        double previewJpegFps,
        int windowSeconds,
        long windowUpdateIntervalMs,
        double hrMinHz,
        double hrMaxHz,
        String csvPath,
        QualityMode qualityMode,
        double qualityThreshold,
        double quality2SnrLow,
        double quality2SnrHigh,
        double quality2MarginLow,
        double quality2MarginHigh,
        boolean quality2HarmonicEnabled,
        double quality2HarmonicLow,
        double quality2HarmonicHigh,
        double quality2SnrWeight,
        double quality2MarginWeight,
        double quality2HarmonicWeight,
        boolean skinEnabled,
        double skinMinCoverage,
        boolean skinFallbackToUnmasked,
        boolean illumEnabled,
        double illumRegressionWindowSeconds,
        double maxStepPerUpdateBpm,
        boolean temporalNormalizationEnabled,
        double temporalNormalizationEps,
        SignalMethod signalMethod,
        RoiMode roiMode,
        double roiForeheadWeight,
        double roiLeftCheekWeight,
        double roiRightCheekWeight,
        int extractorTemporalWindow,
        double autoFallbackMinHoldSeconds,
        int autoLowQualityUpdatesThreshold,
        double autoSwitchCooldownSeconds,
        double autoRecoveryCooldownSeconds,
        double autoProbeWindowSeconds,
        double autoProbeValidRatioThreshold,
        double autoProbeQualityMargin,
        boolean autoUseQuality2ForGating,
        double noFaceWarningSeconds,
        double lowLightBrightnessThreshold,
        double motionThreshold,
        long motionFreezeMinMs,
        long motionResetAfterMs
) {
    public static Config defaults() {
        return new Config(
                0,
                640,
                480,
                30.0,
                0.2,
                0.2,
                10.0,
                30,
                2000L,
                0.8,
                2.5,
                "./logs/rppg.csv",
                QualityMode.SNR,
                0.20,
                2.0,
                8.0,
                1.1,
                2.5,
                true,
                0.05,
                0.35,
                0.6,
                0.3,
                0.1,
                true,
                0.25,
                true,
                true,
                30.0,
                8.0,
                true,
                1e-6,
                SignalMethod.AUTO,
                RoiMode.MULTI,
                0.30,
                0.35,
                0.35,
                32,
                8.0,
                3,
                8.0,
                20.0,
                12.0,
                0.60,
                0.0,
                true,
                2.0,
                45.0,
                0.10,
                300L,
                3000L
        );
    }

    public Config withCsvPath(String value) {
        return new Config(
                cameraIndex,
                targetWidth,
                targetHeight,
                targetFps,
                faceSmoothingAlpha,
                faceSmoothingMaxStep,
                previewJpegFps,
                windowSeconds,
                windowUpdateIntervalMs,
                hrMinHz,
                hrMaxHz,
                value,
                qualityMode,
                qualityThreshold,
                quality2SnrLow,
                quality2SnrHigh,
                quality2MarginLow,
                quality2MarginHigh,
                quality2HarmonicEnabled,
                quality2HarmonicLow,
                quality2HarmonicHigh,
                quality2SnrWeight,
                quality2MarginWeight,
                quality2HarmonicWeight,
                skinEnabled,
                skinMinCoverage,
                skinFallbackToUnmasked,
                illumEnabled,
                illumRegressionWindowSeconds,
                maxStepPerUpdateBpm,
                temporalNormalizationEnabled,
                temporalNormalizationEps,
                signalMethod,
                roiMode,
                roiForeheadWeight,
                roiLeftCheekWeight,
                roiRightCheekWeight,
                extractorTemporalWindow,
                autoFallbackMinHoldSeconds,
                autoLowQualityUpdatesThreshold,
                autoSwitchCooldownSeconds,
                autoRecoveryCooldownSeconds,
                autoProbeWindowSeconds,
                autoProbeValidRatioThreshold,
                autoProbeQualityMargin,
                autoUseQuality2ForGating,
                noFaceWarningSeconds,
                lowLightBrightnessThreshold,
                motionThreshold,
                motionFreezeMinMs,
                motionResetAfterMs
        );
    }
}
